version: '3.8'

services:
  backend:
    # build: .
    image: ghcr.io/epoch8/rtk-call-manager:0.1.0
    restart: always
    volumes:
      - ./:/app
    env_file:
      - .env
    networks:
      - rasa

networks:
  rasa:
    external: true
